/* soapStub.h
   Generated by gSOAP 2.8.66 for moveout.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20866
# error "GSOAP VERSION 20866 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class _ns1__DoOuterRCAVMvou;	/* moveout.h:148 */
class _ns1__DoOuterRCAVMvouResponse;	/* moveout.h:151 */
struct __ns1__DoOuterRCAVMvou;	/* moveout.h:355 */
struct __ns1__DoOuterRCAVMvou_;	/* moveout.h:425 */

/* moveout.h:148 */
#ifndef SOAP_TYPE__ns1__DoOuterRCAVMvou
#define SOAP_TYPE__ns1__DoOuterRCAVMvou (8)
/* complex XSD type 'ns1:DoOuterRCAVMvou': */
class SOAP_CMAC _ns1__DoOuterRCAVMvou {
      public:
        /// Optional element 'ns1:xmlInput' of XSD type 'xsd:string'
        std::string *xmlInput;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__DoOuterRCAVMvou
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__DoOuterRCAVMvou; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__DoOuterRCAVMvou, default initialized and not managed by a soap context
        virtual _ns1__DoOuterRCAVMvou *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__DoOuterRCAVMvou); }
      public:
        /// Constructor with initializations
        _ns1__DoOuterRCAVMvou() : xmlInput(), soap() { }
        virtual ~_ns1__DoOuterRCAVMvou() { }
        /// Friend allocator used by soap_new__ns1__DoOuterRCAVMvou(struct soap*, int)
        friend SOAP_FMAC1 _ns1__DoOuterRCAVMvou * SOAP_FMAC2 soap_instantiate__ns1__DoOuterRCAVMvou(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* moveout.h:151 */
#ifndef SOAP_TYPE__ns1__DoOuterRCAVMvouResponse
#define SOAP_TYPE__ns1__DoOuterRCAVMvouResponse (9)
/* complex XSD type 'ns1:DoOuterRCAVMvouResponse': */
class SOAP_CMAC _ns1__DoOuterRCAVMvouResponse {
      public:
        /// Optional element 'ns1:DoOuterRCAVMvouResult' of XSD type 'xsd:string'
        std::string *DoOuterRCAVMvouResult;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__DoOuterRCAVMvouResponse
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__DoOuterRCAVMvouResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__DoOuterRCAVMvouResponse, default initialized and not managed by a soap context
        virtual _ns1__DoOuterRCAVMvouResponse *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__DoOuterRCAVMvouResponse); }
      public:
        /// Constructor with initializations
        _ns1__DoOuterRCAVMvouResponse() : DoOuterRCAVMvouResult(), soap() { }
        virtual ~_ns1__DoOuterRCAVMvouResponse() { }
        /// Friend allocator used by soap_new__ns1__DoOuterRCAVMvouResponse(struct soap*, int)
        friend SOAP_FMAC1 _ns1__DoOuterRCAVMvouResponse * SOAP_FMAC2 soap_instantiate__ns1__DoOuterRCAVMvouResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* moveout.h:355 */
#ifndef SOAP_TYPE___ns1__DoOuterRCAVMvou
#define SOAP_TYPE___ns1__DoOuterRCAVMvou (16)
/* Wrapper: */
struct SOAP_CMAC __ns1__DoOuterRCAVMvou {
      public:
        /** Optional element 'ns1:DoOuterRCAVMvou' of XSD type 'ns1:DoOuterRCAVMvou' */
        _ns1__DoOuterRCAVMvou *ns1__DoOuterRCAVMvou;
      public:
        /** Return unique type id SOAP_TYPE___ns1__DoOuterRCAVMvou */
        long soap_type() const { return SOAP_TYPE___ns1__DoOuterRCAVMvou; }
        /** Constructor with member initializations */
        __ns1__DoOuterRCAVMvou() : ns1__DoOuterRCAVMvou() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __ns1__DoOuterRCAVMvou * SOAP_FMAC2 soap_instantiate___ns1__DoOuterRCAVMvou(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* moveout.h:425 */
#ifndef SOAP_TYPE___ns1__DoOuterRCAVMvou_
#define SOAP_TYPE___ns1__DoOuterRCAVMvou_ (18)
/* Wrapper: */
struct SOAP_CMAC __ns1__DoOuterRCAVMvou_ {
      public:
        /** Optional element 'ns1:DoOuterRCAVMvou' of XSD type 'ns1:DoOuterRCAVMvou' */
        _ns1__DoOuterRCAVMvou *ns1__DoOuterRCAVMvou;
      public:
        /** Return unique type id SOAP_TYPE___ns1__DoOuterRCAVMvou_ */
        long soap_type() const { return SOAP_TYPE___ns1__DoOuterRCAVMvou_; }
        /** Constructor with member initializations */
        __ns1__DoOuterRCAVMvou_() : ns1__DoOuterRCAVMvou() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __ns1__DoOuterRCAVMvou_ * SOAP_FMAC2 soap_instantiate___ns1__DoOuterRCAVMvou_(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* moveout.h:516 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* moveout.h:516 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* moveout.h:516 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* moveout.h:516 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* moveout.h:516 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (10)
#endif

/* _ns1__DoOuterRCAVMvouResponse has binding name '_ns1__DoOuterRCAVMvouResponse' for type '' */
#ifndef SOAP_TYPE__ns1__DoOuterRCAVMvouResponse
#define SOAP_TYPE__ns1__DoOuterRCAVMvouResponse (9)
#endif

/* _ns1__DoOuterRCAVMvou has binding name '_ns1__DoOuterRCAVMvou' for type '' */
#ifndef SOAP_TYPE__ns1__DoOuterRCAVMvou
#define SOAP_TYPE__ns1__DoOuterRCAVMvou (8)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (28)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (27)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (21)
#endif

/* _ns1__DoOuterRCAVMvou * has binding name 'PointerTo_ns1__DoOuterRCAVMvou' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__DoOuterRCAVMvou
#define SOAP_TYPE_PointerTo_ns1__DoOuterRCAVMvou (13)
#endif

/* std::string * has binding name 'PointerTostd__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (11)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
