/* movein.h
   Generated by wsdl2h 2.8.66 from ./TEST_MOVE_IN.wsdl and typemap.dat
   2018-05-03 13:48:55 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on movein.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -Onum to optimize output by removing unused schema components.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
//gsoap ns1   schema namespace:	http://tempuri.org/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _ns1__DoOuterRCAVMvin.
class _ns1__DoOuterRCAVMvin;

//  Forward declaration of class _ns1__DoOuterRCAVMvinResponse.
class _ns1__DoOuterRCAVMvinResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvin
/// @brief "http://tempuri.org/":DoOuterRCAVMvin is a complexType.
///
/// class _ns1__DoOuterRCAVMvin operations:
/// - _ns1__DoOuterRCAVMvin* soap_new__ns1__DoOuterRCAVMvin(soap*) allocate and default initialize
/// - _ns1__DoOuterRCAVMvin* soap_new__ns1__DoOuterRCAVMvin(soap*, int num) allocate array and default initialize values
/// - _ns1__DoOuterRCAVMvin* soap_new_req__ns1__DoOuterRCAVMvin(soap*, ...) allocate, set required members
/// - _ns1__DoOuterRCAVMvin* soap_new_set__ns1__DoOuterRCAVMvin(soap*, ...) allocate, set all public members
/// - _ns1__DoOuterRCAVMvin::soap_default(soap*) default initialize members
/// - int soap_read__ns1__DoOuterRCAVMvin(soap*, _ns1__DoOuterRCAVMvin*) deserialize from a stream
/// - int soap_write__ns1__DoOuterRCAVMvin(soap*, _ns1__DoOuterRCAVMvin*) serialize to a stream
/// - _ns1__DoOuterRCAVMvin* _ns1__DoOuterRCAVMvin::soap_dup(soap*) returns deep copy of _ns1__DoOuterRCAVMvin, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__DoOuterRCAVMvin::soap_del() deep deletes _ns1__DoOuterRCAVMvin data members, use only after _ns1__DoOuterRCAVMvin::soap_dup(NULL) (use soapcpp2 -Ed)
class _ns1__DoOuterRCAVMvin
{ public:
/// Element "xmlInput" of XSD type xs:string.
    std::string*                         xmlInput                       0;	///< Optional element.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvinResponse
/// @brief "http://tempuri.org/":DoOuterRCAVMvinResponse is a complexType.
///
/// class _ns1__DoOuterRCAVMvinResponse operations:
/// - _ns1__DoOuterRCAVMvinResponse* soap_new__ns1__DoOuterRCAVMvinResponse(soap*) allocate and default initialize
/// - _ns1__DoOuterRCAVMvinResponse* soap_new__ns1__DoOuterRCAVMvinResponse(soap*, int num) allocate array and default initialize values
/// - _ns1__DoOuterRCAVMvinResponse* soap_new_req__ns1__DoOuterRCAVMvinResponse(soap*, ...) allocate, set required members
/// - _ns1__DoOuterRCAVMvinResponse* soap_new_set__ns1__DoOuterRCAVMvinResponse(soap*, ...) allocate, set all public members
/// - _ns1__DoOuterRCAVMvinResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__DoOuterRCAVMvinResponse(soap*, _ns1__DoOuterRCAVMvinResponse*) deserialize from a stream
/// - int soap_write__ns1__DoOuterRCAVMvinResponse(soap*, _ns1__DoOuterRCAVMvinResponse*) serialize to a stream
/// - _ns1__DoOuterRCAVMvinResponse* _ns1__DoOuterRCAVMvinResponse::soap_dup(soap*) returns deep copy of _ns1__DoOuterRCAVMvinResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__DoOuterRCAVMvinResponse::soap_del() deep deletes _ns1__DoOuterRCAVMvinResponse data members, use only after _ns1__DoOuterRCAVMvinResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class _ns1__DoOuterRCAVMvinResponse
{ public:
/// Element "DoOuterRCAVMvinResult" of XSD type xs:string.
    std::string*                         DoOuterRCAVMvinResult          0;	///< Optional element.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	OuterRCAVMvinServiceSoap 
//gsoap ns1  service type:	OuterRCAVMvinServiceSoap 
//gsoap ns1  service port:	http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx 
//gsoap ns1  service namespace:	http://tempuri.org/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref OuterRCAVMvinServiceSoap

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page OuterRCAVMvinServiceSoap Binding "OuterRCAVMvinServiceSoap"

@section OuterRCAVMvinServiceSoap_operations Operations of Binding "OuterRCAVMvinServiceSoap"

  - @ref __ns1__DoOuterRCAVMvin

  - @ref __ns1__DoOuterRCAVMvin_

@section OuterRCAVMvinServiceSoap_ports Default endpoints of Binding "OuterRCAVMvinServiceSoap"

  - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   OuterRCAVMvinServiceSoap                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__DoOuterRCAVMvin                                                   *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__DoOuterRCAVMvin" of service binding "OuterRCAVMvinServiceSoap".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvinResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__DoOuterRCAVMvin(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,
    // output parameters:
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__DoOuterRCAVMvin(
    struct soap *soap,
    // input parameters:
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,
    // output parameters:
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvinServiceSoapProxy.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvinServiceSoapService.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	DoOuterRCAVMvin SOAP
//gsoap ns1  service method-style:	DoOuterRCAVMvin document
//gsoap ns1  service method-encoding:	DoOuterRCAVMvin literal
//gsoap ns1  service method-input-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvin
//gsoap ns1  service method-output-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvinResponse
int __ns1__DoOuterRCAVMvin(
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,	///< Input parameter
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__DoOuterRCAVMvin_                                                  *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__DoOuterRCAVMvin_" of service binding "OuterRCAVMvinServiceSoap".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvinResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__DoOuterRCAVMvin_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,
    // output parameters:
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__DoOuterRCAVMvin_(
    struct soap *soap,
    // input parameters:
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,
    // output parameters:
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvinServiceSoapProxy.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvinServiceSoapService.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	DoOuterRCAVMvin_ SOAP
//gsoap ns1  service method-style:	DoOuterRCAVMvin_ document
//gsoap ns1  service method-encoding:	DoOuterRCAVMvin_ literal
//gsoap ns1  service method-input-action:	DoOuterRCAVMvin_ http://tempuri.org/DoOuterRCAVMvin
//gsoap ns1  service method-output-action:	DoOuterRCAVMvin_ http://tempuri.org/DoOuterRCAVMvinResponse
int __ns1__DoOuterRCAVMvin_(
    _ns1__DoOuterRCAVMvin*              ns1__DoOuterRCAVMvin,	///< Input parameter
    _ns1__DoOuterRCAVMvinResponse      &ns1__DoOuterRCAVMvinResponse	///< Output parameter
);

/**

@page OuterRCAVMvinServiceSoap Binding "OuterRCAVMvinServiceSoap"

@section OuterRCAVMvinServiceSoap_policy_enablers Policy Enablers of Binding "OuterRCAVMvinServiceSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://tempuri.org/"

  - <ns1:DoOuterRCAVMvin> @ref _ns1__DoOuterRCAVMvin
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__DoOuterRCAVMvin(struct soap*, _ns1__DoOuterRCAVMvin*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__DoOuterRCAVMvin(struct soap*, _ns1__DoOuterRCAVMvin*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__DoOuterRCAVMvin(struct soap*, const char *URL, _ns1__DoOuterRCAVMvin*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__DoOuterRCAVMvin(struct soap*, const char *URL, _ns1__DoOuterRCAVMvin*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__DoOuterRCAVMvin(struct soap*, const char *URL, _ns1__DoOuterRCAVMvin*);
    soap_POST_recv__ns1__DoOuterRCAVMvin(struct soap*, _ns1__DoOuterRCAVMvin*);
    @endcode

  - <ns1:DoOuterRCAVMvinResponse> @ref _ns1__DoOuterRCAVMvinResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__DoOuterRCAVMvinResponse(struct soap*, _ns1__DoOuterRCAVMvinResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__DoOuterRCAVMvinResponse(struct soap*, _ns1__DoOuterRCAVMvinResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _ns1__DoOuterRCAVMvinResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _ns1__DoOuterRCAVMvinResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _ns1__DoOuterRCAVMvinResponse*);
    soap_POST_recv__ns1__DoOuterRCAVMvinResponse(struct soap*, _ns1__DoOuterRCAVMvinResponse*);
    @endcode

*/

/* End of movein.h */
