/* move.h
   Generated by wsdl2h 2.8.66 from D:\TEST_MOVE_IN.wsdl D:\TEST_MOVE_OUT.wsdl and typemap.dat
   2018-05-03 15:00:24 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on move.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -Onum to optimize output by removing unused schema components.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

VC1 = "http://tempuri.org/"

*/

#define SOAP_NAMESPACE_OF_VC1	"http://tempuri.org/"
//gsoap VC1   schema namespace:	http://tempuri.org/
//gsoap VC1   schema elementForm:	qualified
//gsoap VC1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _VC1__DoOuterRCAVMvin.
class _VC1__DoOuterRCAVMvin;

//  Forward declaration of class _VC1__DoOuterRCAVMvinResponse.
class _VC1__DoOuterRCAVMvinResponse;

//  Forward declaration of class _VC1__DoOuterRCAVMvou.
class _VC1__DoOuterRCAVMvou;

//  Forward declaration of class _VC1__DoOuterRCAVMvouResponse.
class _VC1__DoOuterRCAVMvouResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvin
/// @brief "http://tempuri.org/":DoOuterRCAVMvin is a complexType.
///
/// class _VC1__DoOuterRCAVMvin operations:
/// - _VC1__DoOuterRCAVMvin* soap_new__VC1__DoOuterRCAVMvin(soap*) allocate and default initialize
/// - _VC1__DoOuterRCAVMvin* soap_new__VC1__DoOuterRCAVMvin(soap*, int num) allocate array and default initialize values
/// - _VC1__DoOuterRCAVMvin* soap_new_req__VC1__DoOuterRCAVMvin(soap*, ...) allocate, set required members
/// - _VC1__DoOuterRCAVMvin* soap_new_set__VC1__DoOuterRCAVMvin(soap*, ...) allocate, set all public members
/// - _VC1__DoOuterRCAVMvin::soap_default(soap*) default initialize members
/// - int soap_read__VC1__DoOuterRCAVMvin(soap*, _VC1__DoOuterRCAVMvin*) deserialize from a stream
/// - int soap_write__VC1__DoOuterRCAVMvin(soap*, _VC1__DoOuterRCAVMvin*) serialize to a stream
/// - _VC1__DoOuterRCAVMvin* _VC1__DoOuterRCAVMvin::soap_dup(soap*) returns deep copy of _VC1__DoOuterRCAVMvin, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _VC1__DoOuterRCAVMvin::soap_del() deep deletes _VC1__DoOuterRCAVMvin data members, use only after _VC1__DoOuterRCAVMvin::soap_dup(NULL) (use soapcpp2 -Ed)
class _VC1__DoOuterRCAVMvin
{ public:
/// Element "xmlInput" of XSD type xs:string.
    std::string*                         xmlInput                       0;	///< Optional element.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvinResponse
/// @brief "http://tempuri.org/":DoOuterRCAVMvinResponse is a complexType.
///
/// class _VC1__DoOuterRCAVMvinResponse operations:
/// - _VC1__DoOuterRCAVMvinResponse* soap_new__VC1__DoOuterRCAVMvinResponse(soap*) allocate and default initialize
/// - _VC1__DoOuterRCAVMvinResponse* soap_new__VC1__DoOuterRCAVMvinResponse(soap*, int num) allocate array and default initialize values
/// - _VC1__DoOuterRCAVMvinResponse* soap_new_req__VC1__DoOuterRCAVMvinResponse(soap*, ...) allocate, set required members
/// - _VC1__DoOuterRCAVMvinResponse* soap_new_set__VC1__DoOuterRCAVMvinResponse(soap*, ...) allocate, set all public members
/// - _VC1__DoOuterRCAVMvinResponse::soap_default(soap*) default initialize members
/// - int soap_read__VC1__DoOuterRCAVMvinResponse(soap*, _VC1__DoOuterRCAVMvinResponse*) deserialize from a stream
/// - int soap_write__VC1__DoOuterRCAVMvinResponse(soap*, _VC1__DoOuterRCAVMvinResponse*) serialize to a stream
/// - _VC1__DoOuterRCAVMvinResponse* _VC1__DoOuterRCAVMvinResponse::soap_dup(soap*) returns deep copy of _VC1__DoOuterRCAVMvinResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _VC1__DoOuterRCAVMvinResponse::soap_del() deep deletes _VC1__DoOuterRCAVMvinResponse data members, use only after _VC1__DoOuterRCAVMvinResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class _VC1__DoOuterRCAVMvinResponse
{ public:
/// Element "DoOuterRCAVMvinResult" of XSD type xs:string.
    std::string*                         DoOuterRCAVMvinResult          0;	///< Optional element.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvou
/// @brief "http://tempuri.org/":DoOuterRCAVMvou is a complexType.
///
/// class _VC1__DoOuterRCAVMvou operations:
/// - _VC1__DoOuterRCAVMvou* soap_new__VC1__DoOuterRCAVMvou(soap*) allocate and default initialize
/// - _VC1__DoOuterRCAVMvou* soap_new__VC1__DoOuterRCAVMvou(soap*, int num) allocate array and default initialize values
/// - _VC1__DoOuterRCAVMvou* soap_new_req__VC1__DoOuterRCAVMvou(soap*, ...) allocate, set required members
/// - _VC1__DoOuterRCAVMvou* soap_new_set__VC1__DoOuterRCAVMvou(soap*, ...) allocate, set all public members
/// - _VC1__DoOuterRCAVMvou::soap_default(soap*) default initialize members
/// - int soap_read__VC1__DoOuterRCAVMvou(soap*, _VC1__DoOuterRCAVMvou*) deserialize from a stream
/// - int soap_write__VC1__DoOuterRCAVMvou(soap*, _VC1__DoOuterRCAVMvou*) serialize to a stream
/// - _VC1__DoOuterRCAVMvou* _VC1__DoOuterRCAVMvou::soap_dup(soap*) returns deep copy of _VC1__DoOuterRCAVMvou, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _VC1__DoOuterRCAVMvou::soap_del() deep deletes _VC1__DoOuterRCAVMvou data members, use only after _VC1__DoOuterRCAVMvou::soap_dup(NULL) (use soapcpp2 -Ed)
class _VC1__DoOuterRCAVMvou
{ public:
/// Element "xmlInput" of XSD type xs:string.
    std::string*                         xmlInput                       0;	///< Optional element.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":DoOuterRCAVMvouResponse
/// @brief "http://tempuri.org/":DoOuterRCAVMvouResponse is a complexType.
///
/// class _VC1__DoOuterRCAVMvouResponse operations:
/// - _VC1__DoOuterRCAVMvouResponse* soap_new__VC1__DoOuterRCAVMvouResponse(soap*) allocate and default initialize
/// - _VC1__DoOuterRCAVMvouResponse* soap_new__VC1__DoOuterRCAVMvouResponse(soap*, int num) allocate array and default initialize values
/// - _VC1__DoOuterRCAVMvouResponse* soap_new_req__VC1__DoOuterRCAVMvouResponse(soap*, ...) allocate, set required members
/// - _VC1__DoOuterRCAVMvouResponse* soap_new_set__VC1__DoOuterRCAVMvouResponse(soap*, ...) allocate, set all public members
/// - _VC1__DoOuterRCAVMvouResponse::soap_default(soap*) default initialize members
/// - int soap_read__VC1__DoOuterRCAVMvouResponse(soap*, _VC1__DoOuterRCAVMvouResponse*) deserialize from a stream
/// - int soap_write__VC1__DoOuterRCAVMvouResponse(soap*, _VC1__DoOuterRCAVMvouResponse*) serialize to a stream
/// - _VC1__DoOuterRCAVMvouResponse* _VC1__DoOuterRCAVMvouResponse::soap_dup(soap*) returns deep copy of _VC1__DoOuterRCAVMvouResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _VC1__DoOuterRCAVMvouResponse::soap_del() deep deletes _VC1__DoOuterRCAVMvouResponse data members, use only after _VC1__DoOuterRCAVMvouResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class _VC1__DoOuterRCAVMvouResponse
{ public:
/// Element "DoOuterRCAVMvouResult" of XSD type xs:string.
    std::string*                         DoOuterRCAVMvouResult          0;	///< Optional element.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap VCWeb service name:	OuterRCAVMvinServiceSoap 
//gsoap VCWeb service type:	OuterRCAVMvinServiceSoap 
//gsoap VCWeb service port:	http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx 
//gsoap VCWeb service namespace:	http://tempuri.org/OuterRCAVMvinServiceSoap 
//gsoap VCWeb service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap VCWeb2 service name:	OuterRCAVMvinServiceSoap12 
//gsoap VCWeb2 service type:	OuterRCAVMvinServiceSoap 
//gsoap VCWeb2 service port:	http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx 
//gsoap VCWeb2 service namespace:	http://tempuri.org/OuterRCAVMvinServiceSoap12 
//gsoap VCWeb2 service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap VCWeb3 service name:	OuterRCAVMvouServiceSoap 
//gsoap VCWeb3 service type:	OuterRCAVMvouServiceSoap 
//gsoap VCWeb3 service port:	http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx 
//gsoap VCWeb3 service namespace:	http://tempuri.org/OuterRCAVMvouServiceSoap 
//gsoap VCWeb3 service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap VCWeb4 service name:	OuterRCAVMvouServiceSoap12 
//gsoap VCWeb4 service type:	OuterRCAVMvouServiceSoap 
//gsoap VCWeb4 service port:	http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx 
//gsoap VCWeb4 service namespace:	http://tempuri.org/OuterRCAVMvouServiceSoap12 
//gsoap VCWeb4 service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage WSDL Definitions

@section WSDL_bindings Service Bindings

  - @ref OuterRCAVMvinServiceSoap

  - @ref OuterRCAVMvinServiceSoap12

  - @ref OuterRCAVMvouServiceSoap

  - @ref OuterRCAVMvouServiceSoap12

@section WSDL_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page OuterRCAVMvinServiceSoap Binding "OuterRCAVMvinServiceSoap"

@section OuterRCAVMvinServiceSoap_operations Operations of Binding "OuterRCAVMvinServiceSoap"

  - @ref __VCWeb__DoOuterRCAVMvin

@section OuterRCAVMvinServiceSoap_ports Default endpoints of Binding "OuterRCAVMvinServiceSoap"

  - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx


*/

/**

@page OuterRCAVMvinServiceSoap12 Binding "OuterRCAVMvinServiceSoap12"

@section OuterRCAVMvinServiceSoap12_operations Operations of Binding "OuterRCAVMvinServiceSoap12"

  - @ref __VCWeb2__DoOuterRCAVMvin

@section OuterRCAVMvinServiceSoap12_ports Default endpoints of Binding "OuterRCAVMvinServiceSoap12"

  - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx


*/

/**

@page OuterRCAVMvouServiceSoap Binding "OuterRCAVMvouServiceSoap"

@section OuterRCAVMvouServiceSoap_operations Operations of Binding "OuterRCAVMvouServiceSoap"

  - @ref __VCWeb3__DoOuterRCAVMvou

@section OuterRCAVMvouServiceSoap_ports Default endpoints of Binding "OuterRCAVMvouServiceSoap"

  - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx


*/

/**

@page OuterRCAVMvouServiceSoap12 Binding "OuterRCAVMvouServiceSoap12"

@section OuterRCAVMvouServiceSoap12_operations Operations of Binding "OuterRCAVMvouServiceSoap12"

  - @ref __VCWeb4__DoOuterRCAVMvou

@section OuterRCAVMvouServiceSoap12_ports Default endpoints of Binding "OuterRCAVMvouServiceSoap12"

  - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   OuterRCAVMvinServiceSoap                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __VCWeb__DoOuterRCAVMvin                                                 *
 *                                                                            *
\******************************************************************************/


/** Operation "__VCWeb__DoOuterRCAVMvin" of service binding "OuterRCAVMvinServiceSoap".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvinResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___VCWeb__DoOuterRCAVMvin(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,
    // output parameters:
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __VCWeb__DoOuterRCAVMvin(
    struct soap *soap,
    // input parameters:
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,
    // output parameters:
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvinServiceSoapProxy.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvinServiceSoapService.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap VCWeb service method-protocol:	DoOuterRCAVMvin SOAP
//gsoap VCWeb service method-style:	DoOuterRCAVMvin document
//gsoap VCWeb service method-encoding:	DoOuterRCAVMvin literal
//gsoap VCWeb service method-input-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvin
//gsoap VCWeb service method-output-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvinResponse
int __VCWeb__DoOuterRCAVMvin(
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,	///< Input parameter
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse	///< Output parameter
);

/**

@page OuterRCAVMvinServiceSoap Binding "OuterRCAVMvinServiceSoap"

@section OuterRCAVMvinServiceSoap_policy_enablers Policy Enablers of Binding "OuterRCAVMvinServiceSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   OuterRCAVMvinServiceSoap12                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __VCWeb2__DoOuterRCAVMvin                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__VCWeb2__DoOuterRCAVMvin" of service binding "OuterRCAVMvinServiceSoap12".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvinService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvin"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvinResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___VCWeb2__DoOuterRCAVMvin(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,
    // output parameters:
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __VCWeb2__DoOuterRCAVMvin(
    struct soap *soap,
    // input parameters:
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,
    // output parameters:
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvinServiceSoap12Proxy.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoap12Proxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvinServiceSoap12Service.h generated with soapcpp2):
@code
  class OuterRCAVMvinServiceSoap12Service;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap VCWeb2 service method-protocol:	DoOuterRCAVMvin SOAP
//gsoap VCWeb2 service method-style:	DoOuterRCAVMvin document
//gsoap VCWeb2 service method-encoding:	DoOuterRCAVMvin literal
//gsoap VCWeb2 service method-input-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvin
//gsoap VCWeb2 service method-output-action:	DoOuterRCAVMvin http://tempuri.org/DoOuterRCAVMvinResponse
int __VCWeb2__DoOuterRCAVMvin(
    _VC1__DoOuterRCAVMvin*              VC1__DoOuterRCAVMvin,	///< Input parameter
    _VC1__DoOuterRCAVMvinResponse      &VC1__DoOuterRCAVMvinResponse	///< Output parameter
);

/**

@page OuterRCAVMvinServiceSoap12 Binding "OuterRCAVMvinServiceSoap12"

@section OuterRCAVMvinServiceSoap12_policy_enablers Policy Enablers of Binding "OuterRCAVMvinServiceSoap12"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   OuterRCAVMvouServiceSoap                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __VCWeb3__DoOuterRCAVMvou                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__VCWeb3__DoOuterRCAVMvou" of service binding "OuterRCAVMvouServiceSoap".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvou"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvou"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvouResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___VCWeb3__DoOuterRCAVMvou(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,
    // output parameters:
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __VCWeb3__DoOuterRCAVMvou(
    struct soap *soap,
    // input parameters:
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,
    // output parameters:
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvouServiceSoapProxy.h generated with soapcpp2):
@code
  class OuterRCAVMvouServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvouServiceSoapService.h generated with soapcpp2):
@code
  class OuterRCAVMvouServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap VCWeb3 service method-protocol:	DoOuterRCAVMvou SOAP
//gsoap VCWeb3 service method-style:	DoOuterRCAVMvou document
//gsoap VCWeb3 service method-encoding:	DoOuterRCAVMvou literal
//gsoap VCWeb3 service method-input-action:	DoOuterRCAVMvou http://tempuri.org/DoOuterRCAVMvou
//gsoap VCWeb3 service method-output-action:	DoOuterRCAVMvou http://tempuri.org/DoOuterRCAVMvouResponse
int __VCWeb3__DoOuterRCAVMvou(
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,	///< Input parameter
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse	///< Output parameter
);

/**

@page OuterRCAVMvouServiceSoap Binding "OuterRCAVMvouServiceSoap"

@section OuterRCAVMvouServiceSoap_policy_enablers Policy Enablers of Binding "OuterRCAVMvouServiceSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   OuterRCAVMvouServiceSoap12                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __VCWeb4__DoOuterRCAVMvou                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__VCWeb4__DoOuterRCAVMvou" of service binding "OuterRCAVMvouServiceSoap12".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://tncmes07/COG/ChipMOS/WebService/OuterRCAVMvouService.asmx

  - Default SOAP action or REST location path:
    - "http://tempuri.org/DoOuterRCAVMvou"

  - Addressing input action: "http://tempuri.org/DoOuterRCAVMvou"

  - Addressing output action: "http://tempuri.org/DoOuterRCAVMvouResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___VCWeb4__DoOuterRCAVMvou(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,
    // output parameters:
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __VCWeb4__DoOuterRCAVMvou(
    struct soap *soap,
    // input parameters:
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,
    // output parameters:
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse
  );
@endcode

C++ proxy class (defined in soapOuterRCAVMvouServiceSoap12Proxy.h generated with soapcpp2):
@code
  class OuterRCAVMvouServiceSoap12Proxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapOuterRCAVMvouServiceSoap12Service.h generated with soapcpp2):
@code
  class OuterRCAVMvouServiceSoap12Service;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap VCWeb4 service method-protocol:	DoOuterRCAVMvou SOAP
//gsoap VCWeb4 service method-style:	DoOuterRCAVMvou document
//gsoap VCWeb4 service method-encoding:	DoOuterRCAVMvou literal
//gsoap VCWeb4 service method-input-action:	DoOuterRCAVMvou http://tempuri.org/DoOuterRCAVMvou
//gsoap VCWeb4 service method-output-action:	DoOuterRCAVMvou http://tempuri.org/DoOuterRCAVMvouResponse
int __VCWeb4__DoOuterRCAVMvou(
    _VC1__DoOuterRCAVMvou*              VC1__DoOuterRCAVMvou,	///< Input parameter
    _VC1__DoOuterRCAVMvouResponse      &VC1__DoOuterRCAVMvouResponse	///< Output parameter
);

/**

@page OuterRCAVMvouServiceSoap12 Binding "OuterRCAVMvouServiceSoap12"

@section OuterRCAVMvouServiceSoap12_policy_enablers Policy Enablers of Binding "OuterRCAVMvouServiceSoap12"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section VC1 Top-level root elements of schema "http://tempuri.org/"

  - <VC1:DoOuterRCAVMvin> @ref _VC1__DoOuterRCAVMvin
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__VC1__DoOuterRCAVMvin(struct soap*, _VC1__DoOuterRCAVMvin*);
    // Writer (returns SOAP_OK on success):
    soap_write__VC1__DoOuterRCAVMvin(struct soap*, _VC1__DoOuterRCAVMvin*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__VC1__DoOuterRCAVMvin(struct soap*, const char *URL, _VC1__DoOuterRCAVMvin*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__VC1__DoOuterRCAVMvin(struct soap*, const char *URL, _VC1__DoOuterRCAVMvin*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__VC1__DoOuterRCAVMvin(struct soap*, const char *URL, _VC1__DoOuterRCAVMvin*);
    soap_POST_recv__VC1__DoOuterRCAVMvin(struct soap*, _VC1__DoOuterRCAVMvin*);
    @endcode

  - <VC1:DoOuterRCAVMvinResponse> @ref _VC1__DoOuterRCAVMvinResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__VC1__DoOuterRCAVMvinResponse(struct soap*, _VC1__DoOuterRCAVMvinResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__VC1__DoOuterRCAVMvinResponse(struct soap*, _VC1__DoOuterRCAVMvinResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__VC1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvinResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__VC1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvinResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__VC1__DoOuterRCAVMvinResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvinResponse*);
    soap_POST_recv__VC1__DoOuterRCAVMvinResponse(struct soap*, _VC1__DoOuterRCAVMvinResponse*);
    @endcode

  - <VC1:DoOuterRCAVMvou> @ref _VC1__DoOuterRCAVMvou
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__VC1__DoOuterRCAVMvou(struct soap*, _VC1__DoOuterRCAVMvou*);
    // Writer (returns SOAP_OK on success):
    soap_write__VC1__DoOuterRCAVMvou(struct soap*, _VC1__DoOuterRCAVMvou*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__VC1__DoOuterRCAVMvou(struct soap*, const char *URL, _VC1__DoOuterRCAVMvou*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__VC1__DoOuterRCAVMvou(struct soap*, const char *URL, _VC1__DoOuterRCAVMvou*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__VC1__DoOuterRCAVMvou(struct soap*, const char *URL, _VC1__DoOuterRCAVMvou*);
    soap_POST_recv__VC1__DoOuterRCAVMvou(struct soap*, _VC1__DoOuterRCAVMvou*);
    @endcode

  - <VC1:DoOuterRCAVMvouResponse> @ref _VC1__DoOuterRCAVMvouResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__VC1__DoOuterRCAVMvouResponse(struct soap*, _VC1__DoOuterRCAVMvouResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__VC1__DoOuterRCAVMvouResponse(struct soap*, _VC1__DoOuterRCAVMvouResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__VC1__DoOuterRCAVMvouResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvouResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__VC1__DoOuterRCAVMvouResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvouResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__VC1__DoOuterRCAVMvouResponse(struct soap*, const char *URL, _VC1__DoOuterRCAVMvouResponse*);
    soap_POST_recv__VC1__DoOuterRCAVMvouResponse(struct soap*, _VC1__DoOuterRCAVMvouResponse*);
    @endcode

*/

/* End of move.h */
